// LOCALHOST
### Get all users
GET https://localhost:3000/contacts

### Get a single user
GET https://localhost:3000/contacts/69b34bb55bdec5a669ca0f7c

### Create a new user
POST https://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.doe@example.com",
    "favoriteColor": "blue",
    "birthday": "1990-01-01"
}


### Update a user
PUT https://localhost:3000/contacts/69b632fcaf2a1dfa3a90fbf9 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "Sample",
    "email": "fakeName@example.com",
    "favoriteColor": "ivory",
    "birthday": "1847-01-01"
}

### Delete a user
DELETE https://localhost:3000/contacts/69b63259af2a1dfa3a90fbf8 HTTP/1.1
